export {default as pantsImg1} from './images/assortment-beige-tone-colored-pants.jpg'
export {default as bagImg} from './images/bag-hanging-from-furniture-item-indoors.jpg'
export {default as bedromImg} from './images/bedroom-background-zoom-calls.jpg'
export {default as applewatch} from './images/digital-speedometer-glows-modern-car-dashboard-generated-by-ai.jpg'
export {default as tops} from './images/fast-fashion-concept-with-full-clothing-store.jpg'
export {default as pots} from './images/grayscale-overhead-shot-metal-pot-frying-pan-lid.jpg'
export {default as makeupkit} from './images/model-career-kit-still-life-flat-lay (1).jpg'
export {default as HeelandBag} from './images/model-career-kit-still-life.jpg'
export {default as menshoe} from './images/assortment-beige-tone-colored-pants.jpg'
export {default as smartwatch} from './images/rendering-smart-home-device (1).jpg'
export {default as earpod} from './images/rendering-smart-home-device.jpg'
export {default as plentyshoe} from './images/still-life-say-no-fast-fashion.jpg'
export {default as monitor} from './images/view-computer-monitor-display.jpg'
export {default as shirt} from './images/view-hawaiian-shirt-with-garland-smartwatch.jpg'
export {default as shirts} from './images/view-hawaiian-shirts-with-coffee-cup-hat.jpg'
export {default as womentops} from './images/wardrobe-with-clothes-hangers.jpg'
export {default as xbox} from './images/xbos.png'
export {default as laptopgame} from './images/laptop.png'
export {default as playstation} from './images/playstation.jpeg'
export {default as oculus} from './images/oculus.jpeg'
export {default as nintendo} from './images/nintendo.png'
export {default as headset} from './images/headsets.jpeg'
export {default as controller} from './images/controllers.png'
export {default as notfound} from './images/Product hunt-cuate.svg'
// export {default as pantsImg1} from './images/assortment-beige-tone-colored-pants.jpg'
// export {default as pantsImg1} from './images/assortment-beige-tone-colored-pants.jpg'
// export {default as pantsImg1} from './images/assortment-beige-tone-colored-pants.jpg'
